Repository mbrg/genai-attacks, pull requests merged in 2024-09, with the labels that each got.

#68 i67 - Misc. fixes for existing entries
  procedure/copilot_m365_lures_victims_into_a_phishing_site.json
  procedure/exfiltration_of_personal_information_from_chatgpt_via_prompt_injection.json
  procedure/financial_transaction_hijacking_with_copilot_as_an_insider.json
  technique/active_scanning.json
  technique/embedded_knowledge_exposure.json
  technique/these_arent_the_droids.json
Labels: content

#73 Audit log evasion procedure
  procedure/microsoft_copilot_purview_audit_log_evasion_and_dlp_bypass.json
Labels: content

#76 Document SlackAI public channel targeted RAG attack
  .vscode/settings.json
  entity/jonathan_cefalu.json
  entity/promptarmor.json
  platform/slackai.json
  procedure/data_exfiltration_from_slack_ai_via_indirect_prompt_injection.json
  technique/compromised_user.json
  technique/prompt_injection.json
Labels: content

#87 Apply tests and fold menu by default
  .pre-commit-config.yaml
  .vscode/settings.json
  book.toml
  entity/gal_malka.json
  entity/lana_salameh.json
Labels: dev

#89 Add support for mitigation
  .pre-commit-config.yaml
  build_scripts/generate_content_as_md.py
  build_scripts/rewrite_mdbook_links.py
  entity/pliny.json
  mitigation/content_security_policy.json
  mitigation/index_based_browsing.json
  mitigation/url_anchoring.json
  platform/microsoft_copilot.json
  procedure/exfiltration_of_personal_information_from_chatgpt_via_prompt_injection.json
  procedure/financial_transaction_hijacking_with_m365_copilot_as_an_insider.json
  procedure/github_copilot_chat_from_prompt_injection_to_data_exfiltration.json
  procedure/microsoft_copilot_purview_audit_log_evasion_and_dlp_bypass.json
  schema/common.schema.json
  schema/mitigation.schema.json
  tactic/command_and_control.json
  technique/clickable_link_rendering.json
  technique/image_rendering.json
  technique/url_familiarizing.json
  technique/web_request_triggering.json
  tests/file_name_test.py
  tests/object_name_test.py
  tests/test_utils.py
Labels: content, dev

#80 i79 - Added Initial Access technique: Guest User Abuse
  technique/guest_user_abuse.json
Labels: content

#83 i81 - Added Recon technique: Finding RAG-indexed targets
  technique/finding_rag_indexed_targets.json
Labels: content

#91 Introduce subtechniques
  .vscode/settings.json
  build_scripts/generate_content_as_md.py
  entity/dmitry_lozovoy.json
  schema/common.schema.json
  technique/off_target_language.json
  technique/system_instruction_keywords.json
  tests/object_ref_test.py
Labels: content, dev
