Repository mbrg/genai-attacks, pull requests merged in 2024-10, with the labels that each got.

#95 Updated 'dmitry_lozovoy.json'
  entity/dmitry_lozovoy.json
Labels: content

#101 Change domain
  readme.md
Labels: dev

#98 i97 - Elaborate common issues in dev docs
  contribute.md
Labels: content, dev

#93 i92 - Added Cresendo tecnique and additional fixes
  entity/ahmed_salem.json
  entity/ronen_eldan.json
  procedure/chatgpt_and_gemini_jailbreak_using_the_crescendo_technique.json
  procedure/data_exfiltration_from_slack_ai_via_indirect_prompt_injection.json
  technique/crescendo.json
  technique/off_target_language.json
Labels: content

#104 i103 - Fix readme file link
  readme.md
Labels: content

#106 Add analytics script to the end of the <head> section
  build_scripts/rewrite_mdbook_links.py
Labels: dev

#110 Adjust rendered mdbook
  .gitignore
  book.toml
  build_scripts/rewrite_mdbook_links.py
Labels: dev
